version: '3.8'

services:
  database:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_SENHA}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - "${DB_PORT_HOST}:${DB_PORT_CONTAINER}"

  front-end:
    build:
      context: ./classificacao-front
      dockerfile: front.dockerfile
    image: ${NOME_IMAGEM_FRONT}
    container_name: ${NOME_CONTAINER_FRONT}
    ports:
      - "${PORT_HOST_FRONT}:${PORT_CONTAINER_FRONT}"
    volumes:
      - ./classificacao-front:/app
      - /app/node_modules
    command: npm run dev

volumes:
  pgdata: