services:
  database:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_SENHA}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init_scripts:/docker-entrypoint-initdb.d
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    container_name: ${DB_NOME_CONTAINER}

  front:
    depends_on: 
        api:
          condition: service_started
    build:
        context: ./classificacao-front
        dockerfile: front.dockerfile
        target: dev
    image: ${FRONT_NOME_IMAGEM}
    container_name: ${FRONT_NOME_CONTAINER}
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    volumes:
      - ./classificacao-front:/app
      - /app/node_modules

  api:
    depends_on: 
      database:
        condition: service_started
    build: 
      context: ./api
      dockerfile: api.dockerfile
      target: dev
    image: ${API_NOME_IMAGEM}
    container_name: ${API_NOME_CONTAINER}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./api:/app
    environment:
      FRONT_URL: "http://localhost:${FRONT_PORT}"
      API_PORT: ${API_PORT}
      DATABASE_URL: "postgresql://${DB_USERNAME}:${DB_SENHA}@database:${DB_PORT}/${DB_NAME}"
  langchain:
    depends_on:
      database:
        condition: service_started
    build: 
      context: ./langchain
      dockerfile: langchain.dockerfile
    restart: unless-stopped
    image: ${LANGCHAIN_NOME_IMAGEM}
    container_name: ${LANGCHAIN_NOME_CONTAINER}
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SIMILARITY_THRESHOLD: ${SIMILARITY_THRESHOLD}
      DB_URL: "postgresql://${DB_USERNAME}:${DB_SENHA}@database:${DB_PORT}/${DB_NAME}"
    volumes:
      - ./otimizacao-tags:/app/otimizacao-tags

volumes:
  pgdata: